(ns SNOBOL4clojure.test-worm1000
  "Machine-generated worm test suite — 1000 programs, band by band.
   Generated by Claude acting as the worm generator.
   Each test encodes ONE semantic fact about SNOBOL4.
   Sections:
     1  Integer literals (0..20, negatives, large)
     2  String literals
     3  Real literals
     4  Arithmetic exhaustive (add/sub/mul/div/remdr for small operands)
     5  Left-to-right evaluation (no operator precedence)
     6  Comparisons EQ/NE/LT/GT/LE/GE
     7  String comparisons LGT/IDENT/DIFFER
     8  Negation ~
     9  String concatenation
    10  SIZE
    11  LEN pattern
    12  ANY pattern
    13  NOTANY pattern
    14  SPAN pattern
    15  BREAK pattern
    16  POS / RPOS
    17  TAB / RTAB
    18  REM
    19  Literal pattern match
    20  Capture with . and $
    21  Pattern replace
    22  Goto — unconditional and conditional
    23  Loops
    24  DEFINE and RETURN
    25  FRETURN
    26  String functions: TRIM, REVERSE, DUPL
    27  ASCII / CHAR
    28  REPLACE function
    29  INTEGER / REAL / STRING coercion
    30  DATATYPE
    31  TABLE
    32  ARRAY
    33  Alternation |
    34  ARB
    35  Edge cases
  "
  (:require [clojure.test :refer :all]
            [SNOBOL4clojure.core :refer :all]))

(defmacro prog [& lines]
  `(RUN (CODE ~(clojure.string/join "\n" (map str lines)))))

(deftest worm_int_lit_0
  "I = 0"
  (prog
    "        I = 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_int_lit_1
  "I = 1"
  (prog
    "        I = 1"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_int_lit_2
  "I = 2"
  (prog
    "        I = 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_int_lit_3
  "I = 3"
  (prog
    "        I = 3"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_int_lit_4
  "I = 4"
  (prog
    "        I = 4"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_int_lit_5
  "I = 5"
  (prog
    "        I = 5"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_int_lit_6
  "I = 6"
  (prog
    "        I = 6"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_int_lit_7
  "I = 7"
  (prog
    "        I = 7"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_int_lit_8
  "I = 8"
  (prog
    "        I = 8"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_int_lit_9
  "I = 9"
  (prog
    "        I = 9"
    "end"
  )
    (is (= 9 ($$ (quote I))))
)

(deftest worm_int_lit_10
  "I = 10"
  (prog
    "        I = 10"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_int_lit_11
  "I = 11"
  (prog
    "        I = 11"
    "end"
  )
    (is (= 11 ($$ (quote I))))
)

(deftest worm_int_lit_12
  "I = 12"
  (prog
    "        I = 12"
    "end"
  )
    (is (= 12 ($$ (quote I))))
)

(deftest worm_int_lit_13
  "I = 13"
  (prog
    "        I = 13"
    "end"
  )
    (is (= 13 ($$ (quote I))))
)

(deftest worm_int_lit_14
  "I = 14"
  (prog
    "        I = 14"
    "end"
  )
    (is (= 14 ($$ (quote I))))
)

(deftest worm_int_lit_15
  "I = 15"
  (prog
    "        I = 15"
    "end"
  )
    (is (= 15 ($$ (quote I))))
)

(deftest worm_int_lit_16
  "I = 16"
  (prog
    "        I = 16"
    "end"
  )
    (is (= 16 ($$ (quote I))))
)

(deftest worm_int_lit_17
  "I = 17"
  (prog
    "        I = 17"
    "end"
  )
    (is (= 17 ($$ (quote I))))
)

(deftest worm_int_lit_18
  "I = 18"
  (prog
    "        I = 18"
    "end"
  )
    (is (= 18 ($$ (quote I))))
)

(deftest worm_int_lit_19
  "I = 19"
  (prog
    "        I = 19"
    "end"
  )
    (is (= 19 ($$ (quote I))))
)

(deftest worm_int_lit_20
  "I = 20"
  (prog
    "        I = 20"
    "end"
  )
    (is (= 20 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_10
  "I = -10"
  (prog
    "        I = -10"
    "end"
  )
    (is (= -10 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_9
  "I = -9"
  (prog
    "        I = -9"
    "end"
  )
    (is (= -9 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_8
  "I = -8"
  (prog
    "        I = -8"
    "end"
  )
    (is (= -8 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_7
  "I = -7"
  (prog
    "        I = -7"
    "end"
  )
    (is (= -7 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_6
  "I = -6"
  (prog
    "        I = -6"
    "end"
  )
    (is (= -6 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_5
  "I = -5"
  (prog
    "        I = -5"
    "end"
  )
    (is (= -5 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_4
  "I = -4"
  (prog
    "        I = -4"
    "end"
  )
    (is (= -4 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_3
  "I = -3"
  (prog
    "        I = -3"
    "end"
  )
    (is (= -3 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_2
  "I = -2"
  (prog
    "        I = -2"
    "end"
  )
    (is (= -2 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_1
  "I = -1"
  (prog
    "        I = -1"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_int_lit_99
  "I = 99"
  (prog
    "        I = 99"
    "end"
  )
    (is (= 99 ($$ (quote I))))
)

(deftest worm_int_lit_100
  "I = 100"
  (prog
    "        I = 100"
    "end"
  )
    (is (= 100 ($$ (quote I))))
)

(deftest worm_int_lit_1000
  "I = 1000"
  (prog
    "        I = 1000"
    "end"
  )
    (is (= 1000 ($$ (quote I))))
)

(deftest wormneg_intneg_litneg_neg_100
  "I = -100"
  (prog
    "        I = -100"
    "end"
  )
    (is (= -100 ($$ (quote I))))
)

(deftest worm_str_lit_empty
  "S = ''"
  (prog
    "        S = ''"
    "end"
  )
    (is (= "" ($$ (quote S))))
)

(deftest worm_str_lit_space
  "S = ' '"
  (prog
    "        S = ' '"
    "end"
  )
    (is (= " " ($$ (quote S))))
)

(deftest worm_str_lit_hello
  "S = 'hello'"
  (prog
    "        S = 'hello'"
    "end"
  )
    (is (= "hello" ($$ (quote S))))
)

(deftest worm_str_lit_digits
  "S = '12345'"
  (prog
    "        S = '12345'"
    "end"
  )
    (is (= "12345" ($$ (quote S))))
)

(deftest worm_str_lit_mixed
  "S = 'aB3!'"
  (prog
    "        S = 'aB3!'"
    "end"
  )
    (is (= "aB3!" ($$ (quote S))))
)

(deftest worm_str_lit_long
  "S = 'abcdefghijklmnopqrstuvwxyz'"
  (prog
    "        S = 'abcdefghijklmnopqrstuvwxyz'"
    "end"
  )
    (is (= "abcdefghijklmnopqrstuvwxyz" ($$ (quote S))))
)

(deftest worm_str_lit_upper
  "S = 'HELLO'"
  (prog
    "        S = 'HELLO'"
    "end"
  )
    (is (= "HELLO" ($$ (quote S))))
)

(deftest worm_str_lit_punct
  "S = ',;:.'"
  (prog
    "        S = ',;:.'"
    "end"
  )
    (is (= ",;:." ($$ (quote S))))
)

(deftest worm_str_lit_singleq
  "S = ''"
  (prog
    "        S = ''"
    "end"
  )
    (is (= "" ($$ (quote S))))
)

(deftest worm_real_lit_0p0
  "A = 0.0"
  (prog
    "        A = 0.0"
    "end"
  )
    (is (= 0.0 ($$ (quote A))))
)

(deftest worm_real_lit_1p0
  "A = 1.0"
  (prog
    "        A = 1.0"
    "end"
  )
    (is (= 1.0 ($$ (quote A))))
)

(deftest worm_real_lit_neg_1p0
  "A = -1.0"
  (prog
    "        A = -1.0"
    "end"
  )
    (is (= -1.0 ($$ (quote A))))
)

(deftest worm_real_lit_3p14
  "A = 3.14"
  (prog
    "        A = 3.14"
    "end"
  )
    (is (= 3.14 ($$ (quote A))))
)

(deftest worm_real_lit_0p5
  "A = 0.5"
  (prog
    "        A = 0.5"
    "end"
  )
    (is (= 0.5 ($$ (quote A))))
)

(deftest worm_real_lit_100p0
  "A = 100.0"
  (prog
    "        A = 100.0"
    "end"
  )
    (is (= 100.0 ($$ (quote A))))
)

(deftest worm_real_lit_neg_3p14
  "A = -3.14"
  (prog
    "        A = -3.14"
    "end"
  )
    (is (= -3.14 ($$ (quote A))))
)

(deftest worm_real_lit_1p5
  "A = 1.5"
  (prog
    "        A = 1.5"
    "end"
  )
    (is (= 1.5 ($$ (quote A))))
)

(deftest worm_real_lit_2p5
  "A = 2.5"
  (prog
    "        A = 2.5"
    "end"
  )
    (is (= 2.5 ($$ (quote A))))
)

(deftest worm_real_lit_10p0
  "A = 10.0"
  (prog
    "        A = 10.0"
    "end"
  )
    (is (= 10.0 ($$ (quote A))))
)

(deftest worm_add_0_0
  "I = 0 + 0 => 0"
  (prog
    "        I = 0 + 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_add_0_1
  "I = 0 + 1 => 1"
  (prog
    "        I = 0 + 1"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_add_0_2
  "I = 0 + 2 => 2"
  (prog
    "        I = 0 + 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_add_0_3
  "I = 0 + 3 => 3"
  (prog
    "        I = 0 + 3"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_add_0_4
  "I = 0 + 4 => 4"
  (prog
    "        I = 0 + 4"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_add_0_5
  "I = 0 + 5 => 5"
  (prog
    "        I = 0 + 5"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_1_0
  "I = 1 + 0 => 1"
  (prog
    "        I = 1 + 0"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_add_1_1
  "I = 1 + 1 => 2"
  (prog
    "        I = 1 + 1"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_add_1_2
  "I = 1 + 2 => 3"
  (prog
    "        I = 1 + 2"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_add_1_3
  "I = 1 + 3 => 4"
  (prog
    "        I = 1 + 3"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_add_1_4
  "I = 1 + 4 => 5"
  (prog
    "        I = 1 + 4"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_1_5
  "I = 1 + 5 => 6"
  (prog
    "        I = 1 + 5"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_add_2_0
  "I = 2 + 0 => 2"
  (prog
    "        I = 2 + 0"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_add_2_1
  "I = 2 + 1 => 3"
  (prog
    "        I = 2 + 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_add_2_2
  "I = 2 + 2 => 4"
  (prog
    "        I = 2 + 2"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_add_2_3
  "I = 2 + 3 => 5"
  (prog
    "        I = 2 + 3"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_2_4
  "I = 2 + 4 => 6"
  (prog
    "        I = 2 + 4"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_add_2_5
  "I = 2 + 5 => 7"
  (prog
    "        I = 2 + 5"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_add_3_0
  "I = 3 + 0 => 3"
  (prog
    "        I = 3 + 0"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_add_3_1
  "I = 3 + 1 => 4"
  (prog
    "        I = 3 + 1"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_add_3_2
  "I = 3 + 2 => 5"
  (prog
    "        I = 3 + 2"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_3_3
  "I = 3 + 3 => 6"
  (prog
    "        I = 3 + 3"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_add_3_4
  "I = 3 + 4 => 7"
  (prog
    "        I = 3 + 4"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_add_3_5
  "I = 3 + 5 => 8"
  (prog
    "        I = 3 + 5"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_add_4_0
  "I = 4 + 0 => 4"
  (prog
    "        I = 4 + 0"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_add_4_1
  "I = 4 + 1 => 5"
  (prog
    "        I = 4 + 1"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_4_2
  "I = 4 + 2 => 6"
  (prog
    "        I = 4 + 2"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_add_4_3
  "I = 4 + 3 => 7"
  (prog
    "        I = 4 + 3"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_add_4_4
  "I = 4 + 4 => 8"
  (prog
    "        I = 4 + 4"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_add_4_5
  "I = 4 + 5 => 9"
  (prog
    "        I = 4 + 5"
    "end"
  )
    (is (= 9 ($$ (quote I))))
)

(deftest worm_add_5_0
  "I = 5 + 0 => 5"
  (prog
    "        I = 5 + 0"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_add_5_1
  "I = 5 + 1 => 6"
  (prog
    "        I = 5 + 1"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_add_5_2
  "I = 5 + 2 => 7"
  (prog
    "        I = 5 + 2"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_add_5_3
  "I = 5 + 3 => 8"
  (prog
    "        I = 5 + 3"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_add_5_4
  "I = 5 + 4 => 9"
  (prog
    "        I = 5 + 4"
    "end"
  )
    (is (= 9 ($$ (quote I))))
)

(deftest worm_add_5_5
  "I = 5 + 5 => 10"
  (prog
    "        I = 5 + 5"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_sub_0_0
  "I = 0 - 0 => 0"
  (prog
    "        I = 0 - 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_sub_0_1
  "I = 0 - 1 => -1"
  (prog
    "        I = 0 - 1"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_sub_0_2
  "I = 0 - 2 => -2"
  (prog
    "        I = 0 - 2"
    "end"
  )
    (is (= -2 ($$ (quote I))))
)

(deftest worm_sub_0_3
  "I = 0 - 3 => -3"
  (prog
    "        I = 0 - 3"
    "end"
  )
    (is (= -3 ($$ (quote I))))
)

(deftest worm_sub_0_4
  "I = 0 - 4 => -4"
  (prog
    "        I = 0 - 4"
    "end"
  )
    (is (= -4 ($$ (quote I))))
)

(deftest worm_sub_0_5
  "I = 0 - 5 => -5"
  (prog
    "        I = 0 - 5"
    "end"
  )
    (is (= -5 ($$ (quote I))))
)

(deftest worm_sub_1_0
  "I = 1 - 0 => 1"
  (prog
    "        I = 1 - 0"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_sub_1_1
  "I = 1 - 1 => 0"
  (prog
    "        I = 1 - 1"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_sub_1_2
  "I = 1 - 2 => -1"
  (prog
    "        I = 1 - 2"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_sub_1_3
  "I = 1 - 3 => -2"
  (prog
    "        I = 1 - 3"
    "end"
  )
    (is (= -2 ($$ (quote I))))
)

(deftest worm_sub_1_4
  "I = 1 - 4 => -3"
  (prog
    "        I = 1 - 4"
    "end"
  )
    (is (= -3 ($$ (quote I))))
)

(deftest worm_sub_1_5
  "I = 1 - 5 => -4"
  (prog
    "        I = 1 - 5"
    "end"
  )
    (is (= -4 ($$ (quote I))))
)

(deftest worm_sub_2_0
  "I = 2 - 0 => 2"
  (prog
    "        I = 2 - 0"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_sub_2_1
  "I = 2 - 1 => 1"
  (prog
    "        I = 2 - 1"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_sub_2_2
  "I = 2 - 2 => 0"
  (prog
    "        I = 2 - 2"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_sub_2_3
  "I = 2 - 3 => -1"
  (prog
    "        I = 2 - 3"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_sub_2_4
  "I = 2 - 4 => -2"
  (prog
    "        I = 2 - 4"
    "end"
  )
    (is (= -2 ($$ (quote I))))
)

(deftest worm_sub_2_5
  "I = 2 - 5 => -3"
  (prog
    "        I = 2 - 5"
    "end"
  )
    (is (= -3 ($$ (quote I))))
)

(deftest worm_sub_3_0
  "I = 3 - 0 => 3"
  (prog
    "        I = 3 - 0"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_sub_3_1
  "I = 3 - 1 => 2"
  (prog
    "        I = 3 - 1"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_sub_3_2
  "I = 3 - 2 => 1"
  (prog
    "        I = 3 - 2"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_sub_3_3
  "I = 3 - 3 => 0"
  (prog
    "        I = 3 - 3"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_sub_3_4
  "I = 3 - 4 => -1"
  (prog
    "        I = 3 - 4"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_sub_3_5
  "I = 3 - 5 => -2"
  (prog
    "        I = 3 - 5"
    "end"
  )
    (is (= -2 ($$ (quote I))))
)

(deftest worm_sub_4_0
  "I = 4 - 0 => 4"
  (prog
    "        I = 4 - 0"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_sub_4_1
  "I = 4 - 1 => 3"
  (prog
    "        I = 4 - 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_sub_4_2
  "I = 4 - 2 => 2"
  (prog
    "        I = 4 - 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_sub_4_3
  "I = 4 - 3 => 1"
  (prog
    "        I = 4 - 3"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_sub_4_4
  "I = 4 - 4 => 0"
  (prog
    "        I = 4 - 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_sub_4_5
  "I = 4 - 5 => -1"
  (prog
    "        I = 4 - 5"
    "end"
  )
    (is (= -1 ($$ (quote I))))
)

(deftest worm_sub_5_0
  "I = 5 - 0 => 5"
  (prog
    "        I = 5 - 0"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_sub_5_1
  "I = 5 - 1 => 4"
  (prog
    "        I = 5 - 1"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_sub_5_2
  "I = 5 - 2 => 3"
  (prog
    "        I = 5 - 2"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_sub_5_3
  "I = 5 - 3 => 2"
  (prog
    "        I = 5 - 3"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_sub_5_4
  "I = 5 - 4 => 1"
  (prog
    "        I = 5 - 4"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_sub_5_5
  "I = 5 - 5 => 0"
  (prog
    "        I = 5 - 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_0
  "I = 0 * 0 => 0"
  (prog
    "        I = 0 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_1
  "I = 0 * 1 => 0"
  (prog
    "        I = 0 * 1"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_2
  "I = 0 * 2 => 0"
  (prog
    "        I = 0 * 2"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_3
  "I = 0 * 3 => 0"
  (prog
    "        I = 0 * 3"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_4
  "I = 0 * 4 => 0"
  (prog
    "        I = 0 * 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_0_5
  "I = 0 * 5 => 0"
  (prog
    "        I = 0 * 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_1_0
  "I = 1 * 0 => 0"
  (prog
    "        I = 1 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_1_1
  "I = 1 * 1 => 1"
  (prog
    "        I = 1 * 1"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_mul_1_2
  "I = 1 * 2 => 2"
  (prog
    "        I = 1 * 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_mul_1_3
  "I = 1 * 3 => 3"
  (prog
    "        I = 1 * 3"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_mul_1_4
  "I = 1 * 4 => 4"
  (prog
    "        I = 1 * 4"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_mul_1_5
  "I = 1 * 5 => 5"
  (prog
    "        I = 1 * 5"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_mul_2_0
  "I = 2 * 0 => 0"
  (prog
    "        I = 2 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_2_1
  "I = 2 * 1 => 2"
  (prog
    "        I = 2 * 1"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_mul_2_2
  "I = 2 * 2 => 4"
  (prog
    "        I = 2 * 2"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_mul_2_3
  "I = 2 * 3 => 6"
  (prog
    "        I = 2 * 3"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_mul_2_4
  "I = 2 * 4 => 8"
  (prog
    "        I = 2 * 4"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_mul_2_5
  "I = 2 * 5 => 10"
  (prog
    "        I = 2 * 5"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_mul_3_0
  "I = 3 * 0 => 0"
  (prog
    "        I = 3 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_3_1
  "I = 3 * 1 => 3"
  (prog
    "        I = 3 * 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_mul_3_2
  "I = 3 * 2 => 6"
  (prog
    "        I = 3 * 2"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_mul_3_3
  "I = 3 * 3 => 9"
  (prog
    "        I = 3 * 3"
    "end"
  )
    (is (= 9 ($$ (quote I))))
)

(deftest worm_mul_3_4
  "I = 3 * 4 => 12"
  (prog
    "        I = 3 * 4"
    "end"
  )
    (is (= 12 ($$ (quote I))))
)

(deftest worm_mul_3_5
  "I = 3 * 5 => 15"
  (prog
    "        I = 3 * 5"
    "end"
  )
    (is (= 15 ($$ (quote I))))
)

(deftest worm_mul_4_0
  "I = 4 * 0 => 0"
  (prog
    "        I = 4 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_4_1
  "I = 4 * 1 => 4"
  (prog
    "        I = 4 * 1"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_mul_4_2
  "I = 4 * 2 => 8"
  (prog
    "        I = 4 * 2"
    "end"
  )
    (is (= 8 ($$ (quote I))))
)

(deftest worm_mul_4_3
  "I = 4 * 3 => 12"
  (prog
    "        I = 4 * 3"
    "end"
  )
    (is (= 12 ($$ (quote I))))
)

(deftest worm_mul_4_4
  "I = 4 * 4 => 16"
  (prog
    "        I = 4 * 4"
    "end"
  )
    (is (= 16 ($$ (quote I))))
)

(deftest worm_mul_4_5
  "I = 4 * 5 => 20"
  (prog
    "        I = 4 * 5"
    "end"
  )
    (is (= 20 ($$ (quote I))))
)

(deftest worm_mul_5_0
  "I = 5 * 0 => 0"
  (prog
    "        I = 5 * 0"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_mul_5_1
  "I = 5 * 1 => 5"
  (prog
    "        I = 5 * 1"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_mul_5_2
  "I = 5 * 2 => 10"
  (prog
    "        I = 5 * 2"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_mul_5_3
  "I = 5 * 3 => 15"
  (prog
    "        I = 5 * 3"
    "end"
  )
    (is (= 15 ($$ (quote I))))
)

(deftest worm_mul_5_4
  "I = 5 * 4 => 20"
  (prog
    "        I = 5 * 4"
    "end"
  )
    (is (= 20 ($$ (quote I))))
)

(deftest worm_mul_5_5
  "I = 5 * 5 => 25"
  (prog
    "        I = 5 * 5"
    "end"
  )
    (is (= 25 ($$ (quote I))))
)

(deftest worm_div_0_1
  "I = 0 / 1 => 0 (integer division)"
  (prog
    "        I = 0 / 1"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_0_2
  "I = 0 / 2 => 0 (integer division)"
  (prog
    "        I = 0 / 2"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_0_3
  "I = 0 / 3 => 0 (integer division)"
  (prog
    "        I = 0 / 3"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_0_4
  "I = 0 / 4 => 0 (integer division)"
  (prog
    "        I = 0 / 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_0_5
  "I = 0 / 5 => 0 (integer division)"
  (prog
    "        I = 0 / 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_1_1
  "I = 1 / 1 => 1 (integer division)"
  (prog
    "        I = 1 / 1"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_1_2
  "I = 1 / 2 => 0 (integer division)"
  (prog
    "        I = 1 / 2"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_1_3
  "I = 1 / 3 => 0 (integer division)"
  (prog
    "        I = 1 / 3"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_1_4
  "I = 1 / 4 => 0 (integer division)"
  (prog
    "        I = 1 / 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_1_5
  "I = 1 / 5 => 0 (integer division)"
  (prog
    "        I = 1 / 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_2_1
  "I = 2 / 1 => 2 (integer division)"
  (prog
    "        I = 2 / 1"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_div_2_2
  "I = 2 / 2 => 1 (integer division)"
  (prog
    "        I = 2 / 2"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_2_3
  "I = 2 / 3 => 0 (integer division)"
  (prog
    "        I = 2 / 3"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_2_4
  "I = 2 / 4 => 0 (integer division)"
  (prog
    "        I = 2 / 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_2_5
  "I = 2 / 5 => 0 (integer division)"
  (prog
    "        I = 2 / 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_3_1
  "I = 3 / 1 => 3 (integer division)"
  (prog
    "        I = 3 / 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_div_3_2
  "I = 3 / 2 => 1 (integer division)"
  (prog
    "        I = 3 / 2"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_3_3
  "I = 3 / 3 => 1 (integer division)"
  (prog
    "        I = 3 / 3"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_3_4
  "I = 3 / 4 => 0 (integer division)"
  (prog
    "        I = 3 / 4"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_3_5
  "I = 3 / 5 => 0 (integer division)"
  (prog
    "        I = 3 / 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_4_1
  "I = 4 / 1 => 4 (integer division)"
  (prog
    "        I = 4 / 1"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_div_4_2
  "I = 4 / 2 => 2 (integer division)"
  (prog
    "        I = 4 / 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_div_4_3
  "I = 4 / 3 => 1 (integer division)"
  (prog
    "        I = 4 / 3"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_4_4
  "I = 4 / 4 => 1 (integer division)"
  (prog
    "        I = 4 / 4"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_4_5
  "I = 4 / 5 => 0 (integer division)"
  (prog
    "        I = 4 / 5"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_div_5_1
  "I = 5 / 1 => 5 (integer division)"
  (prog
    "        I = 5 / 1"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_div_5_2
  "I = 5 / 2 => 2 (integer division)"
  (prog
    "        I = 5 / 2"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_div_5_3
  "I = 5 / 3 => 1 (integer division)"
  (prog
    "        I = 5 / 3"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_5_4
  "I = 5 / 4 => 1 (integer division)"
  (prog
    "        I = 5 / 4"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_5_5
  "I = 5 / 5 => 1 (integer division)"
  (prog
    "        I = 5 / 5"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_6_1
  "I = 6 / 1 => 6 (integer division)"
  (prog
    "        I = 6 / 1"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_div_6_2
  "I = 6 / 2 => 3 (integer division)"
  (prog
    "        I = 6 / 2"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_div_6_3
  "I = 6 / 3 => 2 (integer division)"
  (prog
    "        I = 6 / 3"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_div_6_4
  "I = 6 / 4 => 1 (integer division)"
  (prog
    "        I = 6 / 4"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_6_5
  "I = 6 / 5 => 1 (integer division)"
  (prog
    "        I = 6 / 5"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_7_1
  "I = 7 / 1 => 7 (integer division)"
  (prog
    "        I = 7 / 1"
    "end"
  )
    (is (= 7 ($$ (quote I))))
)

(deftest worm_div_7_2
  "I = 7 / 2 => 3 (integer division)"
  (prog
    "        I = 7 / 2"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_div_7_3
  "I = 7 / 3 => 2 (integer division)"
  (prog
    "        I = 7 / 3"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_div_7_4
  "I = 7 / 4 => 1 (integer division)"
  (prog
    "        I = 7 / 4"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_div_7_5
  "I = 7 / 5 => 1 (integer division)"
  (prog
    "        I = 7 / 5"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_0_1
  "REMDR(0,1) => 0"
  (prog
    "        I = REMDR(0,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_0_2
  "REMDR(0,2) => 0"
  (prog
    "        I = REMDR(0,2)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_0_3
  "REMDR(0,3) => 0"
  (prog
    "        I = REMDR(0,3)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_0_4
  "REMDR(0,4) => 0"
  (prog
    "        I = REMDR(0,4)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_0_5
  "REMDR(0,5) => 0"
  (prog
    "        I = REMDR(0,5)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_1_1
  "REMDR(1,1) => 0"
  (prog
    "        I = REMDR(1,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_1_2
  "REMDR(1,2) => 1"
  (prog
    "        I = REMDR(1,2)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_1_3
  "REMDR(1,3) => 1"
  (prog
    "        I = REMDR(1,3)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_1_4
  "REMDR(1,4) => 1"
  (prog
    "        I = REMDR(1,4)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_1_5
  "REMDR(1,5) => 1"
  (prog
    "        I = REMDR(1,5)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_2_1
  "REMDR(2,1) => 0"
  (prog
    "        I = REMDR(2,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_2_2
  "REMDR(2,2) => 0"
  (prog
    "        I = REMDR(2,2)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_2_3
  "REMDR(2,3) => 2"
  (prog
    "        I = REMDR(2,3)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_remdr_2_4
  "REMDR(2,4) => 2"
  (prog
    "        I = REMDR(2,4)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_remdr_2_5
  "REMDR(2,5) => 2"
  (prog
    "        I = REMDR(2,5)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_remdr_3_1
  "REMDR(3,1) => 0"
  (prog
    "        I = REMDR(3,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_3_2
  "REMDR(3,2) => 1"
  (prog
    "        I = REMDR(3,2)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_3_3
  "REMDR(3,3) => 0"
  (prog
    "        I = REMDR(3,3)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_3_4
  "REMDR(3,4) => 3"
  (prog
    "        I = REMDR(3,4)"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_remdr_3_5
  "REMDR(3,5) => 3"
  (prog
    "        I = REMDR(3,5)"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_remdr_4_1
  "REMDR(4,1) => 0"
  (prog
    "        I = REMDR(4,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_4_2
  "REMDR(4,2) => 0"
  (prog
    "        I = REMDR(4,2)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_4_3
  "REMDR(4,3) => 1"
  (prog
    "        I = REMDR(4,3)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_4_4
  "REMDR(4,4) => 0"
  (prog
    "        I = REMDR(4,4)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_4_5
  "REMDR(4,5) => 4"
  (prog
    "        I = REMDR(4,5)"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_remdr_5_1
  "REMDR(5,1) => 0"
  (prog
    "        I = REMDR(5,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_5_2
  "REMDR(5,2) => 1"
  (prog
    "        I = REMDR(5,2)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_5_3
  "REMDR(5,3) => 2"
  (prog
    "        I = REMDR(5,3)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_remdr_5_4
  "REMDR(5,4) => 1"
  (prog
    "        I = REMDR(5,4)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_5_5
  "REMDR(5,5) => 0"
  (prog
    "        I = REMDR(5,5)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_6_1
  "REMDR(6,1) => 0"
  (prog
    "        I = REMDR(6,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_6_2
  "REMDR(6,2) => 0"
  (prog
    "        I = REMDR(6,2)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_6_3
  "REMDR(6,3) => 0"
  (prog
    "        I = REMDR(6,3)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_6_4
  "REMDR(6,4) => 2"
  (prog
    "        I = REMDR(6,4)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_remdr_6_5
  "REMDR(6,5) => 1"
  (prog
    "        I = REMDR(6,5)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_7_1
  "REMDR(7,1) => 0"
  (prog
    "        I = REMDR(7,1)"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_remdr_7_2
  "REMDR(7,2) => 1"
  (prog
    "        I = REMDR(7,2)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_7_3
  "REMDR(7,3) => 1"
  (prog
    "        I = REMDR(7,3)"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_remdr_7_4
  "REMDR(7,4) => 3"
  (prog
    "        I = REMDR(7,4)"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_remdr_7_5
  "REMDR(7,5) => 2"
  (prog
    "        I = REMDR(7,5)"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_ltr_2p3m4
  "I = 2 + 3 * 4 => 20 (left-to-right, no precedence)"
  (prog
    "        I = 2 + 3 * 4"
    "end"
  )
    (is (= 20 ($$ (quote I))))
)

(deftest worm_ltr_10m2p3
  "I = 10 - 2 + 3 => 11 (left-to-right, no precedence)"
  (prog
    "        I = 10 - 2 + 3"
    "end"
  )
    (is (= 11 ($$ (quote I))))
)

(deftest worm_ltr_2m3p4
  "I = 2 * 3 + 4 => 10 (left-to-right, no precedence)"
  (prog
    "        I = 2 * 3 + 4"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_ltr_6d2p1
  "I = 6 / 2 + 1 => 4 (left-to-right, no precedence)"
  (prog
    "        I = 6 / 2 + 1"
    "end"
  )
    (is (= 4 ($$ (quote I))))
)

(deftest worm_ltr_1p2p3
  "I = 1 + 2 + 3 => 6 (left-to-right, no precedence)"
  (prog
    "        I = 1 + 2 + 3"
    "end"
  )
    (is (= 6 ($$ (quote I))))
)

(deftest worm_ltr_5m1m1
  "I = 5 - 1 - 1 => 3 (left-to-right, no precedence)"
  (prog
    "        I = 5 - 1 - 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_cmp_EQ_0_0
  "EQ(0,0) => yes"
  (prog
    "        EQ(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_EQ_1_1
  "EQ(1,1) => yes"
  (prog
    "        EQ(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_EQ_0_1
  "EQ(0,1) => no"
  (prog
    "        EQ(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_EQ_1_0
  "EQ(1,0) => no"
  (prog
    "        EQ(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_EQ_5_3
  "EQ(5,3) => no"
  (prog
    "        EQ(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_EQ_3_5
  "EQ(3,5) => no"
  (prog
    "        EQ(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_EQ_3_3
  "EQ(3,3) => yes"
  (prog
    "        EQ(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_EQ_neg_1_0
  "EQ(-1,0) => no"
  (prog
    "        EQ(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_EQ_0_neg_1
  "EQ(0,-1) => no"
  (prog
    "        EQ(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_NE_0_0
  "NE(0,0) => no"
  (prog
    "        NE(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_NE_1_1
  "NE(1,1) => no"
  (prog
    "        NE(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_NE_0_1
  "NE(0,1) => yes"
  (prog
    "        NE(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_NE_1_0
  "NE(1,0) => yes"
  (prog
    "        NE(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_NE_5_3
  "NE(5,3) => yes"
  (prog
    "        NE(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_NE_3_5
  "NE(3,5) => yes"
  (prog
    "        NE(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_NE_3_3
  "NE(3,3) => no"
  (prog
    "        NE(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_NE_neg_1_0
  "NE(-1,0) => yes"
  (prog
    "        NE(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_NE_0_neg_1
  "NE(0,-1) => yes"
  (prog
    "        NE(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LT_0_0
  "LT(0,0) => no"
  (prog
    "        LT(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LT_1_1
  "LT(1,1) => no"
  (prog
    "        LT(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LT_0_1
  "LT(0,1) => yes"
  (prog
    "        LT(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LT_1_0
  "LT(1,0) => no"
  (prog
    "        LT(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LT_5_3
  "LT(5,3) => no"
  (prog
    "        LT(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LT_3_5
  "LT(3,5) => yes"
  (prog
    "        LT(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LT_3_3
  "LT(3,3) => no"
  (prog
    "        LT(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LT_neg_1_0
  "LT(-1,0) => yes"
  (prog
    "        LT(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LT_0_neg_1
  "LT(0,-1) => no"
  (prog
    "        LT(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_0_0
  "GT(0,0) => no"
  (prog
    "        GT(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_1_1
  "GT(1,1) => no"
  (prog
    "        GT(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_0_1
  "GT(0,1) => no"
  (prog
    "        GT(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_1_0
  "GT(1,0) => yes"
  (prog
    "        GT(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GT_5_3
  "GT(5,3) => yes"
  (prog
    "        GT(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GT_3_5
  "GT(3,5) => no"
  (prog
    "        GT(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_3_3
  "GT(3,3) => no"
  (prog
    "        GT(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_neg_1_0
  "GT(-1,0) => no"
  (prog
    "        GT(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GT_0_neg_1
  "GT(0,-1) => yes"
  (prog
    "        GT(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_0_0
  "LE(0,0) => yes"
  (prog
    "        LE(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_1_1
  "LE(1,1) => yes"
  (prog
    "        LE(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_0_1
  "LE(0,1) => yes"
  (prog
    "        LE(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_1_0
  "LE(1,0) => no"
  (prog
    "        LE(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LE_5_3
  "LE(5,3) => no"
  (prog
    "        LE(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_LE_3_5
  "LE(3,5) => yes"
  (prog
    "        LE(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_3_3
  "LE(3,3) => yes"
  (prog
    "        LE(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_neg_1_0
  "LE(-1,0) => yes"
  (prog
    "        LE(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_LE_0_neg_1
  "LE(0,-1) => no"
  (prog
    "        LE(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GE_0_0
  "GE(0,0) => yes"
  (prog
    "        GE(0,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GE_1_1
  "GE(1,1) => yes"
  (prog
    "        GE(1,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GE_0_1
  "GE(0,1) => no"
  (prog
    "        GE(0,1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GE_1_0
  "GE(1,0) => yes"
  (prog
    "        GE(1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GE_5_3
  "GE(5,3) => yes"
  (prog
    "        GE(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GE_3_5
  "GE(3,5) => no"
  (prog
    "        GE(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GE_3_3
  "GE(3,3) => yes"
  (prog
    "        GE(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_cmp_GE_neg_1_0
  "GE(-1,0) => no"
  (prog
    "        GE(-1,0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_cmp_GE_0_neg_1
  "GE(0,-1) => yes"
  (prog
    "        GE(0,-1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_IDENT_abc_abc
  "IDENT('abc','abc') => yes"
  (prog
    "        IDENT('abc','abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_IDENT_abc_xyz
  "IDENT('abc','xyz') => no"
  (prog
    "        IDENT('abc','xyz') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_strcmp_IDENT_empty_empty
  "IDENT('','') => yes"
  (prog
    "        IDENT('','') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_IDENT_a_empty
  "IDENT('a','') => no"
  (prog
    "        IDENT('a','') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_strcmp_DIFFER_abc_xyz
  "DIFFER('abc','xyz') => yes"
  (prog
    "        DIFFER('abc','xyz') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_DIFFER_abc_abc
  "DIFFER('abc','abc') => no"
  (prog
    "        DIFFER('abc','abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_strcmp_DIFFER_empty_a
  "DIFFER('','a') => yes"
  (prog
    "        DIFFER('','a') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_LGT_b_a
  "LGT('b','a') => yes"
  (prog
    "        LGT('b','a') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_LGT_a_b
  "LGT('a','b') => no"
  (prog
    "        LGT('a','b') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_strcmp_LGT_abc_ab
  "LGT('abc','ab') => yes"
  (prog
    "        LGT('abc','ab') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_strcmp_LGT_a_a
  "LGT('a','a') => no"
  (prog
    "        LGT('a','a') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_strcmp_LGT_B_A
  "LGT('B','A') => yes"
  (prog
    "        LGT('B','A') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_neg_EQ_5_5
  "~EQ(5,5) => no"
  (prog
    "        ~EQ(5,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_neg_EQ_5_6
  "~EQ(5,6) => yes"
  (prog
    "        ~EQ(5,6) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_neg_LT_3_5
  "~LT(3,5) => no"
  (prog
    "        ~LT(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_neg_LT_5_3
  "~LT(5,3) => yes"
  (prog
    "        ~LT(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_neg_GT_5_3
  "~GT(5,3) => no"
  (prog
    "        ~GT(5,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_neg_GT_3_5
  "~GT(3,5) => yes"
  (prog
    "        ~GT(3,5) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_concat_ab
  "S = 'a' 'b' => "ab""
  (prog
    "        S = 'a' 'b'"
    "end"
  )
    (is (= "ab" ($$ (quote S))))
)

(deftest worm_concat_abc
  "S = 'a' 'b' 'c' => "abc""
  (prog
    "        S = 'a' 'b' 'c'"
    "end"
  )
    (is (= "abc" ($$ (quote S))))
)

(deftest worm_concat_empty_left
  "S = '' 'hello' => "hello""
  (prog
    "        S = '' 'hello'"
    "end"
  )
    (is (= "hello" ($$ (quote S))))
)

(deftest worm_concat_empty_right
  "S = 'hello' '' => "hello""
  (prog
    "        S = 'hello' ''"
    "end"
  )
    (is (= "hello" ($$ (quote S))))
)

(deftest worm_concat_both_empty
  "S = '' '' => """
  (prog
    "        S = '' ''"
    "end"
  )
    (is (= "" ($$ (quote S))))
)

(deftest worm_concat_int_str
  "S = 42 'x' => "42x""
  (prog
    "        S = 42 'x'"
    "end"
  )
    (is (= "42x" ($$ (quote S))))
)

(deftest worm_concat_str_int
  "S = 'x' 42 => "x42""
  (prog
    "        S = 'x' 42"
    "end"
  )
    (is (= "x42" ($$ (quote S))))
)

(deftest worm_concat_int_int
  "S = 1 2 => "12""
  (prog
    "        S = 1 2"
    "end"
  )
    (is (= "12" ($$ (quote S))))
)

(deftest worm_concat_spaces
  "S = 'hello' ' ' 'world' => "hello world""
  (prog
    "        S = 'hello' ' ' 'world'"
    "end"
  )
    (is (= "hello world" ($$ (quote S))))
)

(deftest worm_concat_long_concat
  "S = 'foo' 'bar' 'baz' 'qux' => "foobarbazqux""
  (prog
    "        S = 'foo' 'bar' 'baz' 'qux'"
    "end"
  )
    (is (= "foobarbazqux" ($$ (quote S))))
)

(deftest worm_size_empty
  "SIZE('') => 0"
  (prog
    "        I = SIZE('')"
    "end"
  )
    (is (= 0 ($$ (quote I))))
)

(deftest worm_size_one
  "SIZE('a') => 1"
  (prog
    "        I = SIZE('a')"
    "end"
  )
    (is (= 1 ($$ (quote I))))
)

(deftest worm_size_five
  "SIZE('hello') => 5"
  (prog
    "        I = SIZE('hello')"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_size_spaces
  "SIZE('  ') => 2"
  (prog
    "        I = SIZE('  ')"
    "end"
  )
    (is (= 2 ($$ (quote I))))
)

(deftest worm_size_ten
  "SIZE('1234567890') => 10"
  (prog
    "        I = SIZE('1234567890')"
    "end"
  )
    (is (= 10 ($$ (quote I))))
)

(deftest worm_len_0_on_abcde
  "LEN(0) on 'abcde' captures ''"
  (prog
    "        'abcde' POS(0) LEN(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_len_1_on_abcde
  "LEN(1) on 'abcde' captures 'a'"
  (prog
    "        'abcde' POS(0) LEN(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_len_2_on_abcde
  "LEN(2) on 'abcde' captures 'ab'"
  (prog
    "        'abcde' POS(0) LEN(2) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "ab" ($$ (quote C))))
)

(deftest worm_len_3_on_abcde
  "LEN(3) on 'abcde' captures 'abc'"
  (prog
    "        'abcde' POS(0) LEN(3) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_len_5_on_abcde
  "LEN(5) on 'abcde' captures 'abcde'"
  (prog
    "        'abcde' POS(0) LEN(5) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abcde" ($$ (quote C))))
)

(deftest worm_len_6_on_abcde
  "LEN(6) on 'abcde' fails"
  (prog
    "        'abcde' POS(0) LEN(6) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_len_0_on_empty
  "LEN(0) on '' captures ''"
  (prog
    "        '' POS(0) LEN(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_len_1_on_empty
  "LEN(1) on '' fails"
  (prog
    "        '' POS(0) LEN(1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_any_aeiou_on_hello
  "ANY('aeiou') on 'hello' captures 'e'"
  (prog
    "        'hello' ANY('aeiou') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "e" ($$ (quote C))))
)

(deftest worm_any_aeiou_on_aeiou
  "ANY('aeiou') on 'aeiou' captures 'a'"
  (prog
    "        'aeiou' ANY('aeiou') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_any_aeiou_on_bcdfg
  "ANY('aeiou') on 'bcdfg' fails"
  (prog
    "        'bcdfg' ANY('aeiou') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_any_aeiou_on_empty
  "ANY('aeiou') on '' fails"
  (prog
    "        '' ANY('aeiou') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_any_a_on_aaa
  "ANY('a') on 'aaa' captures 'a'"
  (prog
    "        'aaa' ANY('a') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_any_abc_on_xyz
  "ANY('abc') on 'xyz' fails"
  (prog
    "        'xyz' ANY('abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_any_xyz_on_xyzabc
  "ANY('xyz') on 'xyzabc' captures 'x'"
  (prog
    "        'xyzabc' ANY('xyz') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "x" ($$ (quote C))))
)

(deftest worm_notany_aeiou_on_hello
  "NOTANY('aeiou') on 'hello' captures 'h'"
  (prog
    "        'hello' NOTANY('aeiou') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "h" ($$ (quote C))))
)

(deftest worm_notany_aeiou_on_aeiou
  "NOTANY('aeiou') on 'aeiou' fails"
  (prog
    "        'aeiou' NOTANY('aeiou') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_notany_aeiou_on_empty
  "NOTANY('aeiou') on '' fails"
  (prog
    "        '' NOTANY('aeiou') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_notany_abc_on_xyz
  "NOTANY('abc') on 'xyz' captures 'x'"
  (prog
    "        'xyz' NOTANY('abc') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "x" ($$ (quote C))))
)

(deftest worm_notany_xyz_on_xyz
  "NOTANY('xyz') on 'xyz' fails"
  (prog
    "        'xyz' NOTANY('xyz') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_notany_abc_on_abcdef
  "NOTANY('abc') on 'abcdef' fails"
  (prog
    "        'abcdef' NOTANY('abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_span_abc_on_abcdef
  "SPAN('abc') on 'abcdef' captures 'abc'"
  (prog
    "        'abcdef' SPAN('abc') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_span_abc_on_aaabbb
  "SPAN('abc') on 'aaabbb' captures 'aaabbb'"
  (prog
    "        'aaabbb' SPAN('abc') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "aaabbb" ($$ (quote C))))
)

(deftest worm_span_abc_on_xyz
  "SPAN('abc') on 'xyz' fails"
  (prog
    "        'xyz' SPAN('abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_span_abc_on_empty
  "SPAN('abc') on '' fails"
  (prog
    "        '' SPAN('abc') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_span_a_on_aaa
  "SPAN('a') on 'aaa' captures 'aaa'"
  (prog
    "        'aaa' SPAN('a') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "aaa" ($$ (quote C))))
)

(deftest worm_span_abc_on_abcxyz
  "SPAN('abc') on 'abcxyz' captures 'abc'"
  (prog
    "        'abcxyz' SPAN('abc') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_span_0123_on_123abc
  "SPAN('0123456789') on '123abc' captures '123'"
  (prog
    "        '123abc' SPAN('0123456789') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "123" ($$ (quote C))))
)

(deftest worm_span_0123_on_abc
  "SPAN('0123456789') on 'abc' fails"
  (prog
    "        'abc' SPAN('0123456789') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_break_xyz_on_abcxyz
  "BREAK('xyz') on 'abcxyz' captures 'abc'"
  (prog
    "        'abcxyz' BREAK('xyz') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_break_xyz_on_xyzabc
  "BREAK('xyz') on 'xyzabc' captures ''"
  (prog
    "        'xyzabc' BREAK('xyz') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_break_xyz_on_abcdef
  "BREAK('xyz') on 'abcdef' fails"
  (prog
    "        'abcdef' BREAK('xyz') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_break_xyz_on_empty
  "BREAK('xyz') on '' captures ''"
  (prog
    "        '' BREAK('xyz') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_break_a_on_bbbab
  "BREAK('a') on 'bbbab' captures 'bbb'"
  (prog
    "        'bbbab' BREAK('a') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "bbb" ($$ (quote C))))
)

(deftest worm_break__on_hello
  "BREAK('!') on 'hello!' captures 'hello'"
  (prog
    "        'hello!' BREAK('!') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "hello" ($$ (quote C))))
)

(deftest worm_break_0123_on_abc123
  "BREAK('0123456789') on 'abc123' captures 'abc'"
  (prog
    "        'abc123' BREAK('0123456789') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_pos_0_on_abc
  "POS(0) LEN(1) on 'abc' captures 'a'"
  (prog
    "        'abc' POS(0) LEN(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_pos_1_on_abc
  "POS(1) LEN(1) on 'abc' captures 'b'"
  (prog
    "        'abc' POS(1) LEN(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "b" ($$ (quote C))))
)

(deftest worm_pos_2_on_abc
  "POS(2) LEN(1) on 'abc' captures 'c'"
  (prog
    "        'abc' POS(2) LEN(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "c" ($$ (quote C))))
)

(deftest worm_pos_3_on_abc
  "POS(3) LEN(1) on 'abc' fails"
  (prog
    "        'abc' POS(3) LEN(1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_pos_0_on_empty
  "POS(0) LEN(1) on '' fails"
  (prog
    "        '' POS(0) LEN(1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_rpos_0_on_abc
  "LEN(3) RPOS(0) on 'abc'"
  (prog
    "        'abc' POS(0) LEN(3) RPOS(0) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_rpos_1_on_abc
  "LEN(2) RPOS(1) on 'abc'"
  (prog
    "        'abc' POS(0) LEN(2) RPOS(1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_rpos_3_on_abc
  "LEN(0) RPOS(3) on 'abc'"
  (prog
    "        'abc' POS(0) LEN(0) RPOS(3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_rpos_4_on_abc
  "RPOS(4) on 'abc' fails"
  (prog
    "        'abc' POS(0) LEN(0) RPOS(4) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_tab_0_on_abcde
  "TAB(0) on 'abcde' captures ''"
  (prog
    "        'abcde' TAB(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_tab_1_on_abcde
  "TAB(1) on 'abcde' captures 'a'"
  (prog
    "        'abcde' TAB(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_tab_2_on_abcde
  "TAB(2) on 'abcde' captures 'ab'"
  (prog
    "        'abcde' TAB(2) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "ab" ($$ (quote C))))
)

(deftest worm_tab_3_on_abcde
  "TAB(3) on 'abcde' captures 'abc'"
  (prog
    "        'abcde' TAB(3) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_tab_5_on_abcde
  "TAB(5) on 'abcde' captures 'abcde'"
  (prog
    "        'abcde' TAB(5) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abcde" ($$ (quote C))))
)

(deftest worm_tab_6_on_abcde
  "TAB(6) on 'abcde' fails"
  (prog
    "        'abcde' TAB(6) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_tab_0_on_empty
  "TAB(0) on '' captures ''"
  (prog
    "        '' TAB(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_tab_1_on_empty
  "TAB(1) on '' fails"
  (prog
    "        '' TAB(1) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_rtab_0_on_abcde
  "RTAB(0) on 'abcde' captures 'abcde'"
  (prog
    "        'abcde' RTAB(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abcde" ($$ (quote C))))
)

(deftest worm_rtab_1_on_abcde
  "RTAB(1) on 'abcde' captures 'abcd'"
  (prog
    "        'abcde' RTAB(1) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abcd" ($$ (quote C))))
)

(deftest worm_rtab_2_on_abcde
  "RTAB(2) on 'abcde' captures 'abc'"
  (prog
    "        'abcde' RTAB(2) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_rtab_5_on_abcde
  "RTAB(5) on 'abcde' captures ''"
  (prog
    "        'abcde' RTAB(5) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_rtab_6_on_abcde
  "RTAB(6) on 'abcde' fails"
  (prog
    "        'abcde' RTAB(6) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_rtab_0_on_empty
  "RTAB(0) on '' captures ''"
  (prog
    "        '' RTAB(0) . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "" ($$ (quote C))))
)

(deftest worm_rem_after_ab_on_abcde
  "REM after 'ab' on 'abcde' captures 'cde'"
  (prog
    "        'abcde' 'ab' REM . C"
    "end"
  )
    (is (= "cde" ($$ (quote C))))
)

(deftest worm_rem_after_nothing_on_abcde
  "REM after '' on 'abcde' captures 'abcde'"
  (prog
    "        'abcde' '' REM . C"
    "end"
  )
    (is (= "abcde" ($$ (quote C))))
)

(deftest worm_rem_after_abcde_on_abcde
  "REM after 'abcde' on 'abcde' captures ''"
  (prog
    "        'abcde' 'abcde' REM . C"
    "end"
  )
    (is (= "" ($$ (quote C))))
)

(deftest worm_rem_after_hel_on_hello
  "REM after 'hel' on 'hello' captures 'lo'"
  (prog
    "        'hello' 'hel' REM . C"
    "end"
  )
    (is (= "lo" ($$ (quote C))))
)

(deftest worm_rem_after_x_on_x
  "REM after 'x' on 'x' captures ''"
  (prog
    "        'x' 'x' REM . C"
    "end"
  )
    (is (= "" ($$ (quote C))))
)

(deftest worm_litpat_ell_in_hello
  "'ell' in 'hello' => yes"
  (prog
    "        'hello' 'ell' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_hello_in_hello
  "'hello' in 'hello' => yes"
  (prog
    "        'hello' 'hello' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_xyz_in_hello
  "'xyz' in 'hello' => no"
  (prog
    "        'hello' 'xyz' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_litpat_empty_in_hello
  "'' in 'hello' => yes"
  (prog
    "        'hello' '' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_empty_in_empty
  "'' in '' => yes"
  (prog
    "        '' '' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_a_in_empty
  "'a' in '' => no"
  (prog
    "        '' 'a' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_litpat_abc_in_abcabc
  "'abc' in 'abcabc' => yes"
  (prog
    "        'abcabc' 'abc' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_HELL_in_HELLO
  "'HELL' in 'HELLO' => yes"
  (prog
    "        'HELLO' 'HELL' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_litpat_hell_in_HELLO
  "'hell' in 'HELLO' => no"
  (prog
    "        'HELLO' 'hell' :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_capture_dot_cap_from_hello_wo
  "Capture with . : world on 'hello world'"
  (prog
    "        'hello world' world . C"
    "end"
  )
    (is (= "world" ($$ (quote C))))
)

(deftest worm_capture_dot_cap_from_abcde
  "Capture with . : LEN(3) on 'abcde'"
  (prog
    "        'abcde' LEN(3) . C"
    "end"
  )
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_capture_dot_cap_from_abcde_1
  "Capture with . : SPAN('abc') on 'abcde'"
  (prog
    "        'abcde' SPAN('abc') . C"
    "end"
  )
    (is (= "abc" ($$ (quote C))))
)

(deftest worm_capture_dot_cap_from_hello
  "Capture with . : ANY('aeiou') on 'hello'"
  (prog
    "        'hello' ANY('aeiou') . C"
    "end"
  )
    (is (= "e" ($$ (quote C))))
)

(deftest worm_capture_dot_cap_from_12345
  "Capture with . : SPAN('0123456789') on '12345'"
  (prog
    "        '12345' SPAN('0123456789') . C"
    "end"
  )
    (is (= "12345" ($$ (quote C))))
)

(deftest worm_replace_world_on_hello_wo
  "'hello world' 'world' = 'SNOBOL' => 'hello SNOBOL'"
  (prog
    "        S = 'hello world'"
    "        S 'world' = 'SNOBOL'"
    "end"
  )
    (is (= "hello SNOBOL" ($$ (quote S))))
)

(deftest worm_replace_a_on_aaa
  "'aaa' 'a' = 'b' => 'baa'"
  (prog
    "        S = 'aaa'"
    "        S 'a' = 'b'"
    "end"
  )
    (is (= "baa" ($$ (quote S))))
)

(deftest worm_replace_ANYaei_on_hello
  "'hello' ANY('aeiou') = 'X' => 'hXllo'"
  (prog
    "        S = 'hello'"
    "        S ANY('aeiou') = 'X'"
    "end"
  )
    (is (= "hXllo" ($$ (quote S))))
)

(deftest worm_replace_LEN1_on_abc
  "'abc' LEN(1) = 'X' => 'Xbc'"
  (prog
    "        S = 'abc'"
    "        S LEN(1) = 'X'"
    "end"
  )
    (is (= "Xbc" ($$ (quote S))))
)

(deftest worm_replace_xyz_on_hello
  "'hello' 'xyz' = 'Q' => 'hello'"
  (prog
    "        S = 'hello'"
    "        S 'xyz' = 'Q'"
    "end"
  )
    (is (= "hello" ($$ (quote S))))
)

(deftest worm_goto_skip
  "Unconditional goto skips code"
  (prog
    "        R = 'before'"
    "        :(SKIP)"
    "        R = 'skipped'"
    "SKIP    "
    "end"
  )
    (is (= "before" ($$ (quote R))))
)

(deftest worm_goto_end
  ":(END) halts program"
  (prog
    "        R = 'set'"
    "        :(END)"
    "        R = 'never'"
    "END"
  )
    (is (= "set" ($$ (quote R))))
)

(deftest worm_goto_forward_ref
  "Forward reference label resolves"
  (prog
    "        :(TARGET)"
    "        R = 'never'"
    "TARGET  R = 'reached'"
    "end"
  )
    (is (= "reached" ($$ (quote R))))
)

(deftest worm_goto_s_taken
  ":S branch taken on success"
  (prog
    "        EQ(1,1) :S(TAKEN)"
    "        R = 'not taken'   :(END)"
    "TAKEN   R = 'taken'"
    "END"
  )
    (is (= "taken" ($$ (quote R))))
)

(deftest worm_goto_s_not_taken
  ":S branch not taken on failure"
  (prog
    "        EQ(1,2) :S(TAKEN)"
    "        R = 'fell through'   :(END)"
    "TAKEN   R = 'taken'"
    "END"
  )
    (is (= "fell through" ($$ (quote R))))
)

(deftest worm_goto_f_taken
  ":F branch taken on failure"
  (prog
    "        EQ(1,2) :F(TAKEN)"
    "        R = 'not taken'   :(END)"
    "TAKEN   R = 'taken'"
    "END"
  )
    (is (= "taken" ($$ (quote R))))
)

(deftest worm_goto_sf_success
  ":S(x)F(y) — success side"
  (prog
    "        EQ(3,3) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
)

(deftest worm_goto_sf_failure
  ":S(x)F(y) — failure side"
  (prog
    "        EQ(3,4) :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_loop_count_1
  "Count loop 1..1 concatenated = "1""
  (prog
    "        I = 1"
    "        S = ''"
    "LOOP    S = S I"
    "        I = I + 1"
    "        LE(I,1) :S(LOOP)"
    "end"
  )
    (is (= "1" ($$ (quote S))))
)

(deftest worm_loop_count_2
  "Count loop 1..2 concatenated = "12""
  (prog
    "        I = 1"
    "        S = ''"
    "LOOP    S = S I"
    "        I = I + 1"
    "        LE(I,2) :S(LOOP)"
    "end"
  )
    (is (= "12" ($$ (quote S))))
)

(deftest worm_loop_count_3
  "Count loop 1..3 concatenated = "123""
  (prog
    "        I = 1"
    "        S = ''"
    "LOOP    S = S I"
    "        I = I + 1"
    "        LE(I,3) :S(LOOP)"
    "end"
  )
    (is (= "123" ($$ (quote S))))
)

(deftest worm_loop_count_5
  "Count loop 1..5 concatenated = "12345""
  (prog
    "        I = 1"
    "        S = ''"
    "LOOP    S = S I"
    "        I = I + 1"
    "        LE(I,5) :S(LOOP)"
    "end"
  )
    (is (= "12345" ($$ (quote S))))
)

(deftest worm_loop_count_10
  "Count loop 1..10 concatenated = "12345678910""
  (prog
    "        I = 1"
    "        S = ''"
    "LOOP    S = S I"
    "        I = I + 1"
    "        LE(I,10) :S(LOOP)"
    "end"
  )
    (is (= "12345678910" ($$ (quote S))))
)

(deftest worm_loop_sum_1
  "Sum 1..1 = 1"
  (prog
    "        I = 1"
    "        SUM = 0"
    "LOOP    SUM = SUM + I"
    "        I = I + 1"
    "        LE(I,1) :S(LOOP)"
    "end"
  )
    (is (= 1 ($$ (quote SUM))))
)

(deftest worm_loop_sum_3
  "Sum 1..3 = 6"
  (prog
    "        I = 1"
    "        SUM = 0"
    "LOOP    SUM = SUM + I"
    "        I = I + 1"
    "        LE(I,3) :S(LOOP)"
    "end"
  )
    (is (= 6 ($$ (quote SUM))))
)

(deftest worm_loop_sum_5
  "Sum 1..5 = 15"
  (prog
    "        I = 1"
    "        SUM = 0"
    "LOOP    SUM = SUM + I"
    "        I = I + 1"
    "        LE(I,5) :S(LOOP)"
    "end"
  )
    (is (= 15 ($$ (quote SUM))))
)

(deftest worm_define_double_3
  "DOUBLE(N) with arg 3 => 6"
  (prog
    "        DEFINE('DOUBLE(N)') :(DOUBLE_END)"
    "DOUBLE   DOUBLE = N * 2   :(RETURN)"
    "DOUBLE_END"
    "        R = DOUBLE(3)"
    "end"
  )
    (is (= 6 ($$ (quote R))))
)

(deftest worm_define_double_0
  "DOUBLE(N) with arg 0 => 0"
  (prog
    "        DEFINE('DOUBLE(N)') :(DOUBLE_END)"
    "DOUBLE   DOUBLE = N * 2   :(RETURN)"
    "DOUBLE_END"
    "        R = DOUBLE(0)"
    "end"
  )
    (is (= 0 ($$ (quote R))))
)

(deftest worm_define_double_7
  "DOUBLE(N) with arg 7 => 14"
  (prog
    "        DEFINE('DOUBLE(N)') :(DOUBLE_END)"
    "DOUBLE   DOUBLE = N * 2   :(RETURN)"
    "DOUBLE_END"
    "        R = DOUBLE(7)"
    "end"
  )
    (is (= 14 ($$ (quote R))))
)

(deftest worm_define_double_neg_1
  "DOUBLE(N) with arg -1 => -2"
  (prog
    "        DEFINE('DOUBLE(N)') :(DOUBLE_END)"
    "DOUBLE   DOUBLE = N * 2   :(RETURN)"
    "DOUBLE_END"
    "        R = DOUBLE(-1)"
    "end"
  )
    (is (= -2 ($$ (quote R))))
)

(deftest worm_define_triple_2
  "TRIPLE(N) with arg 2 => 6"
  (prog
    "        DEFINE('TRIPLE(N)') :(TRIPLE_END)"
    "TRIPLE   TRIPLE = N * 3   :(RETURN)"
    "TRIPLE_END"
    "        R = TRIPLE(2)"
    "end"
  )
    (is (= 6 ($$ (quote R))))
)

(deftest worm_define_triple_5
  "TRIPLE(N) with arg 5 => 15"
  (prog
    "        DEFINE('TRIPLE(N)') :(TRIPLE_END)"
    "TRIPLE   TRIPLE = N * 3   :(RETURN)"
    "TRIPLE_END"
    "        R = TRIPLE(5)"
    "end"
  )
    (is (= 15 ($$ (quote R))))
)

(deftest worm_define_square_4
  "SQ(N) with arg 4 => 16"
  (prog
    "        DEFINE('SQ(N)') :(SQUARE_END)"
    "SQUARE   SQ = N * N   :(RETURN)"
    "SQUARE_END"
    "        R = SQUARE(4)"
    "end"
  )
    (is (= 16 ($$ (quote R))))
)

(deftest worm_define_square_3
  "SQ(N) with arg 3 => 9"
  (prog
    "        DEFINE('SQ(N)') :(SQUARE_END)"
    "SQUARE   SQ = N * N   :(RETURN)"
    "SQUARE_END"
    "        R = SQUARE(3)"
    "end"
  )
    (is (= 9 ($$ (quote R))))
)

(deftest worm_define_square_0
  "SQ(N) with arg 0 => 0"
  (prog
    "        DEFINE('SQ(N)') :(SQUARE_END)"
    "SQUARE   SQ = N * N   :(RETURN)"
    "SQUARE_END"
    "        R = SQUARE(0)"
    "end"
  )
    (is (= 0 ($$ (quote R))))
)

(deftest worm_define_negate_5
  "NEG(N) with arg 5 => -5"
  (prog
    "        DEFINE('NEG(N)') :(NEGATE_END)"
    "NEGATE   NEG = 0 - N   :(RETURN)"
    "NEGATE_END"
    "        R = NEGATE(5)"
    "end"
  )
    (is (= -5 ($$ (quote R))))
)

(deftest worm_define_negate_neg_3
  "NEG(N) with arg -3 => 3"
  (prog
    "        DEFINE('NEG(N)') :(NEGATE_END)"
    "NEGATE   NEG = 0 - N   :(RETURN)"
    "NEGATE_END"
    "        R = NEGATE(-3)"
    "end"
  )
    (is (= 3 ($$ (quote R))))
)

(deftest worm_define_addone_0
  "INC(N) with arg 0 => 1"
  (prog
    "        DEFINE('INC(N)') :(ADDONE_END)"
    "ADDONE   INC = N + 1   :(RETURN)"
    "ADDONE_END"
    "        R = ADDONE(0)"
    "end"
  )
    (is (= 1 ($$ (quote R))))
)

(deftest worm_define_addone_9
  "INC(N) with arg 9 => 10"
  (prog
    "        DEFINE('INC(N)') :(ADDONE_END)"
    "ADDONE   INC = N + 1   :(RETURN)"
    "ADDONE_END"
    "        R = ADDONE(9)"
    "end"
  )
    (is (= 10 ($$ (quote R))))
)

(deftest worm_define_addone_99
  "INC(N) with arg 99 => 100"
  (prog
    "        DEFINE('INC(N)') :(ADDONE_END)"
    "ADDONE   INC = N + 1   :(RETURN)"
    "ADDONE_END"
    "        R = ADDONE(99)"
    "end"
  )
    (is (= 100 ($$ (quote R))))
)

(deftest worm_freturn_causes_failure
  "FRETURN makes calling statement fail"
  (prog
    "        DEFINE('ALWAYSFAIL()') :(AF_END)"
    "ALWAYSFAIL                     :(FRETURN)"
    "AF_END"
    "        ALWAYSFAIL() :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_freturn_conditional
  "Function returns normally or FRETURNs based on arg"
  (prog
    "        DEFINE('POSCHECK(N)') :(PC_END)"
    "POSCHECK GT(N,0) :F(PC_FAIL)"
    "         POSCHECK = N         :(RETURN)"
    "PC_FAIL                       :(FRETURN)"
    "PC_END"
    "        R1 = POSCHECK(5)  :S(GOT)F(NO)"
    "GOT     R2 = 'ok'         :(END)"
    "NO      R2 = 'fail'"
    "END"
  )
    (is (= 5  ($$ (quote R1))))
    (is (= "ok" ($$ (quote R2))))
)

(deftest worm_trim_trailing
  "TRIM('hello   ') = 'hello'"
  (prog
    "        R = TRIM('hello   ')"
    "end"
  )
    (is (= "hello" ($$ (quote R))))
)

(deftest worm_trim_no_trailing
  "TRIM('hello') = 'hello'"
  (prog
    "        R = TRIM('hello')"
    "end"
  )
    (is (= "hello" ($$ (quote R))))
)

(deftest worm_trim_keeps_leading
  "TRIM('  hello  ') keeps leading spaces"
  (prog
    "        R = TRIM('  hello  ')"
    "end"
  )
    (is (= "  hello" ($$ (quote R))))
)

(deftest worm_reverse_hello
  "REVERSE('hello') = 'olleh'"
  (prog
    "        R = REVERSE('hello')"
    "end"
  )
    (is (= "olleh" ($$ (quote R))))
)

(deftest worm_reverse_empty
  "REVERSE('') = ''"
  (prog
    "        R = REVERSE('')"
    "end"
  )
    (is (= "" ($$ (quote R))))
)

(deftest worm_reverse_single
  "REVERSE('a') = 'a'"
  (prog
    "        R = REVERSE('a')"
    "end"
  )
    (is (= "a" ($$ (quote R))))
)

(deftest worm_dupl_basic
  "DUPL('ab',3) = 'ababab'"
  (prog
    "        R = DUPL('ab',3)"
    "end"
  )
    (is (= "ababab" ($$ (quote R))))
)

(deftest worm_dupl_zero
  "DUPL('ab',0) = ''"
  (prog
    "        R = DUPL('ab',0)"
    "end"
  )
    (is (= "" ($$ (quote R))))
)

(deftest worm_dupl_one
  "DUPL('xyz',1) = 'xyz'"
  (prog
    "        R = DUPL('xyz',1)"
    "end"
  )
    (is (= "xyz" ($$ (quote R))))
)

(deftest worm_ascii_A
  "ASCII('A') = 65"
  (prog
    "        I = ASCII('A')"
    "end"
  )
    (is (= 65 ($$ (quote I))))
)

(deftest worm_ascii_Z
  "ASCII('Z') = 90"
  (prog
    "        I = ASCII('Z')"
    "end"
  )
    (is (= 90 ($$ (quote I))))
)

(deftest worm_ascii_a
  "ASCII('a') = 97"
  (prog
    "        I = ASCII('a')"
    "end"
  )
    (is (= 97 ($$ (quote I))))
)

(deftest worm_ascii_z
  "ASCII('z') = 122"
  (prog
    "        I = ASCII('z')"
    "end"
  )
    (is (= 122 ($$ (quote I))))
)

(deftest worm_ascii_0
  "ASCII('0') = 48"
  (prog
    "        I = ASCII('0')"
    "end"
  )
    (is (= 48 ($$ (quote I))))
)

(deftest worm_ascii_9
  "ASCII('9') = 57"
  (prog
    "        I = ASCII('9')"
    "end"
  )
    (is (= 57 ($$ (quote I))))
)

(deftest worm_ascii_space
  "ASCII(' ') = 32"
  (prog
    "        I = ASCII(' ')"
    "end"
  )
    (is (= 32 ($$ (quote I))))
)

(deftest worm_char_65
  "CHAR(65) = 'A'"
  (prog
    "        C = CHAR(65)"
    "end"
  )
    (is (= "A" ($$ (quote C))))
)

(deftest worm_char_90
  "CHAR(90) = 'Z'"
  (prog
    "        C = CHAR(90)"
    "end"
  )
    (is (= "Z" ($$ (quote C))))
)

(deftest worm_char_97
  "CHAR(97) = 'a'"
  (prog
    "        C = CHAR(97)"
    "end"
  )
    (is (= "a" ($$ (quote C))))
)

(deftest worm_char_48
  "CHAR(48) = '0'"
  (prog
    "        C = CHAR(48)"
    "end"
  )
    (is (= "0" ($$ (quote C))))
)

(deftest worm_char_32
  "CHAR(32) = ' '"
  (prog
    "        C = CHAR(32)"
    "end"
  )
    (is (= " " ($$ (quote C))))
)

(deftest worm_replace_fn_hello
  "REPLACE('hello','aeiou...','AEIOU...') = 'hEllO'"
  (prog
    "        R = REPLACE('hello', 'aeiou', 'AEIOU')"
    "end"
  )
    (is (= "hEllO" ($$ (quote R))))
)

(deftest worm_replace_fn_HELLO
  "REPLACE('HELLO','ABCDEF...','abcdef...') = 'hello'"
  (prog
    "        R = REPLACE('HELLO', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"
    "end"
  )
    (is (= "hello" ($$ (quote R))))
)

(deftest worm_replace_fn_abc
  "REPLACE('abc','abc...','xyz...') = 'xyz'"
  (prog
    "        R = REPLACE('abc', 'abc', 'xyz')"
    "end"
  )
    (is (= "xyz" ($$ (quote R))))
)

(deftest worm_replace_fn_abc_1
  "REPLACE('abc','ab...','XY...') = 'XYc'"
  (prog
    "        R = REPLACE('abc', 'ab', 'XY')"
    "end"
  )
    (is (= "XYc" ($$ (quote R))))
)

(deftest worm_replace_fn_aabbcc
  "REPLACE('aabbcc','abc...','ABC...') = 'AABBCC'"
  (prog
    "        R = REPLACE('aabbcc', 'abc', 'ABC')"
    "end"
  )
    (is (= "AABBCC" ($$ (quote R))))
)

(deftest worm_integer_from_str
  "INTEGER('42') succeeds => 42"
  (prog
    "        I = INTEGER('42') :S(YES)F(NO)"
    "YES     R = I             :(END)"
    "NO      R = 'fail'"
    "END"
  )
    (is (= 42 ($$ (quote R))))
)

(deftest worm_integer_from_int
  "INTEGER(42) succeeds => 42"
  (prog
    "        I = INTEGER(42) :S(YES)F(NO)"
    "YES     R = I           :(END)"
    "NO      R = 'fail'"
    "END"
  )
    (is (= 42 ($$ (quote R))))
)

(deftest worm_integer_from_real
  "INTEGER(3.7) truncates => 3"
  (prog
    "        I = INTEGER(3.7) :S(YES)F(NO)"
    "YES     R = I            :(END)"
    "NO      R = 'fail'"
    "END"
  )
    (is (= 3 ($$ (quote R))))
)

(deftest worm_string_from_int
  "STRING(42) => '42'"
  (prog
    "        R = STRING(42)"
    "end"
  )
    (is (= "42" ($$ (quote R))))
)

(deftest worm_string_from_real
  "STRING(3.14) => '3.14'"
  (prog
    "        R = STRING(3.14)"
    "end"
  )
    (is (= "3.14" ($$ (quote R))))
)

(deftest worm_datatype_string
  "DATATYPE('hello') = "string""
  (prog
    "        R = DATATYPE('hello')"
    "end"
  )
    (is (= "string" ($$ (quote R))))
)

(deftest worm_datatype_integer
  "DATATYPE(42) = "integer""
  (prog
    "        R = DATATYPE(42)"
    "end"
  )
    (is (= "integer" ($$ (quote R))))
)

(deftest worm_datatype_real
  "DATATYPE(3.14) = "real""
  (prog
    "        R = DATATYPE(3.14)"
    "end"
  )
    (is (= "real" ($$ (quote R))))
)

(deftest worm_datatype_pattern
  "DATATYPE(ANY('a')) = "pattern""
  (prog
    "        R = DATATYPE(ANY('a'))"
    "end"
  )
    (is (= "pattern" ($$ (quote R))))
)

(deftest worm_datatype_array
  "DATATYPE(ARRAY(3)) = "array""
  (prog
    "        R = DATATYPE(ARRAY(3))"
    "end"
  )
    (is (= "array" ($$ (quote R))))
)

(deftest worm_datatype_table
  "DATATYPE(TABLE()) = "table""
  (prog
    "        R = DATATYPE(TABLE())"
    "end"
  )
    (is (= "table" ($$ (quote R))))
)

(deftest worm_table_set_get
  "TABLE set and get single key"
  (prog
    "        T = TABLE()"
    "        T<'k'> = 'v'"
    "        R = T<'k'>"
    "end"
  )
    (is (= "v" ($$ (quote R))))
)

(deftest worm_table_integer_key
  "TABLE with integer key"
  (prog
    "        T = TABLE()"
    "        T<1> = 42"
    "        R = T<1>"
    "end"
  )
    (is (= 42 ($$ (quote R))))
)

(deftest worm_table_missing_key
  "TABLE missing key returns empty string"
  (prog
    "        T = TABLE()"
    "        R = T<'missing'>"
    "end"
  )
    (is (= "" ($$ (quote R))))
)

(deftest worm_table_overwrite
  "TABLE overwrite key"
  (prog
    "        T = TABLE()"
    "        T<'x'> = 'first'"
    "        T<'x'> = 'second'"
    "        R = T<'x'>"
    "end"
  )
    (is (= "second" ($$ (quote R))))
)

(deftest worm_table_multiple
  "TABLE multiple distinct keys"
  (prog
    "        T = TABLE()"
    "        T<'a'> = 1"
    "        T<'b'> = 2"
    "        T<'c'> = 3"
    "        R = T<'a'> T<'b'> T<'c'>"
    "end"
  )
    (is (= "123" ($$ (quote R))))
)

(deftest worm_array_set_get_1
  "ARRAY(1) set and get element 1"
  (prog
    "        A = ARRAY(1)"
    "        A<1> = 10"
    "        R = A<1>"
    "end"
  )
    (is (= 10 ($$ (quote R))))
)

(deftest worm_array_set_get_2
  "ARRAY(2) set and get element 2"
  (prog
    "        A = ARRAY(2)"
    "        A<2> = 20"
    "        R = A<2>"
    "end"
  )
    (is (= 20 ($$ (quote R))))
)

(deftest worm_array_set_get_3
  "ARRAY(3) set and get element 3"
  (prog
    "        A = ARRAY(3)"
    "        A<3> = 30"
    "        R = A<3>"
    "end"
  )
    (is (= 30 ($$ (quote R))))
)

(deftest worm_array_set_get_5
  "ARRAY(5) set and get element 5"
  (prog
    "        A = ARRAY(5)"
    "        A<5> = 50"
    "        R = A<5>"
    "end"
  )
    (is (= 50 ($$ (quote R))))
)

(deftest worm_array_set_get_10
  "ARRAY(10) set and get element 10"
  (prog
    "        A = ARRAY(10)"
    "        A<10> = 100"
    "        R = A<10>"
    "end"
  )
    (is (= 100 ($$ (quote R))))
)

(deftest worm_array_default_empty
  "ARRAY unset element is empty string"
  (prog
    "        A = ARRAY(5)"
    "        R = A<3>"
    "end"
  )
    (is (= "" ($$ (quote R))))
)

(deftest worm_array_loop_fill
  "Fill array in loop, read back"
  (prog
    "        A = ARRAY(5)"
    "        I = 1"
    "LOOP    A<I> = I * I"
    "        I = I + 1"
    "        LE(I,5) :S(LOOP)"
    "        R = A<1> A<4> A<5>"
    "end"
  )
    (is (= "1165" ($$ (quote R))))
)

(deftest worm_alt_hello
  "'hello' ('he' | 'wo') captures 'he'"
  (prog
    "        'hello' ('he' | 'wo') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "he" ($$ (quote C))))
)

(deftest worm_alt_world
  "'world' ('he' | 'wo') captures 'wo'"
  (prog
    "        'world' ('he' | 'wo') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "wo" ($$ (quote C))))
)

(deftest worm_alt_xyz
  "'xyz' ('he' | 'wo') fails"
  (prog
    "        'xyz' ('he' | 'wo') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_alt_abc
  "'abc' ('a' | 'b' | 'c') captures 'a'"
  (prog
    "        'abc' ('a' | 'b' | 'c') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "a" ($$ (quote C))))
)

(deftest worm_alt_bcd
  "'bcd' ('a' | 'b' | 'c') captures 'b'"
  (prog
    "        'bcd' ('a' | 'b' | 'c') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "b" ($$ (quote C))))
)

(deftest worm_alt_cde
  "'cde' ('a' | 'b' | 'c') captures 'c'"
  (prog
    "        'cde' ('a' | 'b' | 'c') . C :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "yes" ($$ (quote R))))
    (is (= "c" ($$ (quote C))))
)

(deftest worm_alt_xyz_1
  "'xyz' ('a' | 'b' | 'c') fails"
  (prog
    "        'xyz' ('a' | 'b' | 'c') :S(YES)F(NO)"
    "YES     R = 'yes'   :(END)"
    "NO      R = 'no'"
    "END"
  )
    (is (= "no" ($$ (quote R))))
)

(deftest worm_arb_h_arb_o_in_hello
  "'h' ARB . C 'o' in 'hello' captures 'ell'"
  (prog
    "        'hello' 'h' ARB . C 'o'"
    "end"
  )
    (is (= "ell" ($$ (quote C))))
)

(deftest worm_arb_a_arb_e_in_abcde
  "'a' ARB . C 'e' in 'abcde' captures 'bcd'"
  (prog
    "        'abcde' 'a' ARB . C 'e'"
    "end"
  )
    (is (= "bcd" ($$ (quote C))))
)

(deftest worm_arb_a_arb_a_in_abba
  "'a' ARB . C 'a' in 'abba' captures ''"
  (prog
    "        'abba' 'a' ARB . C 'a'"
    "end"
  )
    (is (= "" ($$ (quote C))))
)

(deftest worm_arb_he_arb_o_in_hello
  "'he' ARB . C 'o' in 'hello' captures 'll'"
  (prog
    "        'hello' 'he' ARB . C 'o'"
    "end"
  )
    (is (= "ll" ($$ (quote C))))
)

(deftest worm_edge_self_concat
  "S = S x — self-concatenation chain"
  (prog
    "        S = 'a'"
    "        S = S 'b'"
    "        S = S 'c'"
    "        S = S 'd'"
    "end"
  )
    (is (= "abcd" ($$ (quote S))))
)

(deftest worm_edge_self_arith
  "I = I + 1 repeated"
  (prog
    "        I = 0"
    "        I = I + 1"
    "        I = I + 1"
    "        I = I + 1"
    "end"
  )
    (is (= 3 ($$ (quote I))))
)

(deftest worm_edge_overwrite_many
  "Multiple assignments to same var — last wins"
  (prog
    "        I = 1"
    "        I = 2"
    "        I = 3"
    "        I = 4"
    "        I = 5"
    "end"
  )
    (is (= 5 ($$ (quote I))))
)

(deftest worm_edge_unassigned_is_empty
  "Unassigned variable reads as empty string"
  (prog
    "        R = UNASSIGNED_VAR"
    "end"
  )
    (is (= "" ($$ (quote R))))
)

(deftest worm_edge_unassigned_in_concat
  "Unassigned var in concat is empty"
  (prog
    "        R = 'hello' UNASSIGNED 'world'"
    "end"
  )
    (is (= "helloworld" ($$ (quote R))))
)

(deftest worm_edge_int_string_coerce
  "String "42" used in arithmetic coerces to 42"
  (prog
    "        I = '42' + 1"
    "end"
  )
    (is (= 43 ($$ (quote I))))
)

(deftest worm_edge_int_to_string_concat
  "Integer used in concat coerces to string"
  (prog
    "        S = 'x' 42 'y'"
    "end"
  )
    (is (= "x42y" ($$ (quote S))))
)

(deftest worm_edge_pattern_var_reuse
  "Pattern var used on multiple subjects"
  (prog
    "        P = ANY('aeiou')"
    "        'hello' P . C1"
    "        'world' P . C2"
    "        'xyz'   P . C3 :S(OK)F(MISS)"
    "OK      C3 = 'found'  :(END)"
    "MISS    C3 = 'none'"
    "END"
  )
    (is (= "e" ($$ (quote C1))))
    (is (= "o" ($$ (quote C2))))
    (is (= "none" ($$ (quote C3))))
)

(deftest worm_edge_multiple_captures
  "Multiple captures in one pattern"
  (prog
    "        'hello world' SPAN('abcdefghijklmnopqrstuvwxyz') . W1                      ' '                      SPAN('abcdefghijklmnopqrstuvwxyz') . W2"
    "end"
  )
    (is (= "hello" ($$ (quote W1))))
    (is (= "world" ($$ (quote W2))))
)

(deftest worm_edge_nested_calls
  "Nested function calls: REVERSE(TRIM(s))"
  (prog
    "        R = REVERSE(TRIM('hello   '))"
    "end"
  )
    (is (= "olleh" ($$ (quote R))))
)

(deftest worm_edge_size_of_concat
  "SIZE of concatenated string"
  (prog
    "        S = 'hello' ' ' 'world'"
    "        I = SIZE(S)"
    "end"
  )
    (is (= 11 ($$ (quote I))))
)

